services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 testdjangoProject.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
